const actionType = {
    LOGIN: 'LOGIN',
    GETHOME: 'GETHOME',
    GET_INFO_SEARCH: ' GET_INFO_SEARCH',
    CHECK_LOGIN: 'CHECK_LOGIN',
    GET_SHOWPOUP : 'GET_SHOWPOPUP',
    GET_SHOWADDPEOPLE: 'GET_SHOWADDPEOPLE'
};
export default actionType;
